### ISSUE TITLE
Improve results list

### ISSUE THREAD

**Issue by Korporal** [mndrix/merge-this#14]
It would be helpful if your table of test results included which of the three tests failed when there is a failure. For example failing in several tests because merge conflicts were raised is better than failing those tests because merge worked but execution tests failed.

I'd love to know where Git fails these tests where it does fail also why do you consider a merge conflict a failure anyway?

Perhaps the results should have three columns for each system - merged, builds, runs ?

If this is easy I'd love to see these - also have you blogged about this? there is very little out there that talks about the risks of merging cleanly when bugs may have been introduced.

Thx

**Comment by mndrix** [comment]
> It would be helpful if your table of test results included which of the three tests failed when there is a failure

In the current test suite, nearly all the failures are from merge conflicts so adding this to the table doesn't change it much.  If the distribution of failures changes as I add more merge scenarios, I will definitely consider adding this info to the table.


> I'd love to know where Git fails these tests

Git fails all tests with a merge conflict.


> why do you consider a merge conflict a failure anyway?

Each scenario in the test suite can be resolve unambiguously without a merge conflict.  Any tool which produces a merge conflict has fallen short of that ideal.


> also have you blogged about this? there is very little out there that talks about the risks of merging cleanly when bugs may have been introduced.

I haven't blogged about this, but I completely agree about the danger of introducing bugs during a merge conflict.  That's the main reason that this test suite compiles and executes the result of the merge conflict.  In practice, most tools are so conservative in their merge strategies that they rarely introduce code errors during a clean merge.

If you can come up with a merge scenario which causes one of these tools to merge cleanly but produce incorrect output, I would love a pull request so that we can document and test it.

Thanks for your thoughts on the project.
